# Generated by Django 4.1.1 on 2022-10-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitcoin',
            fields=[
                ('timestamp', models.TimeField(max_length=264, primary_key=True, serialize=False, unique=True)),
                ('price', models.IntegerField(max_length=264)),
            ],
        ),
    ]
