# Generated by Django 4.1.1 on 2022-10-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoin',
            name='price',
            field=models.IntegerField(),
        ),
    ]
