# Generated by Django 4.1.1 on 2022-10-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0002_alter_bitcoin_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoin',
            name='price',
            field=models.FloatField(),
        ),
    ]
